# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formulario.ui'
#
# Created: Mon Sep  5 21:44:12 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_formulario(object):
    def setupUi(self, formulario):
        formulario.setObjectName("formulario")
        formulario.resize(389, 320)
        formulario.setMinimumSize(QtCore.QSize(389, 320))
        formulario.setMaximumSize(QtCore.QSize(389, 320))
        self.centralWidget = QtGui.QWidget(formulario)
        self.centralWidget.setObjectName("centralWidget")
        self.add = QtGui.QPushButton(self.centralWidget)
        self.add.setGeometry(QtCore.QRect(130, 270, 121, 41))
        self.add.setObjectName("add")
        self.t_noticia = QtGui.QLineEdit(self.centralWidget)
        self.t_noticia.setGeometry(QtCore.QRect(10, 40, 371, 22))
        self.t_noticia.setObjectName("t_noticia")
        self.resumen = QtGui.QLineEdit(self.centralWidget)
        self.resumen.setGeometry(QtCore.QRect(10, 70, 371, 21))
        self.resumen.setMaxLength(1000000)
        self.resumen.setObjectName("resumen")
        self.dia = QtGui.QLineEdit(self.centralWidget)
        self.dia.setGeometry(QtCore.QRect(80, 10, 31, 21))
        self.dia.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dia.setObjectName("dia")
        self.autor = QtGui.QLineEdit(self.centralWidget)
        self.autor.setGeometry(QtCore.QRect(10, 260, 113, 22))
        self.autor.setObjectName("autor")
        self.txt_noticia = QtGui.QTextEdit(self.centralWidget)
        self.txt_noticia.setGeometry(QtCore.QRect(10, 120, 371, 70))
        self.txt_noticia.setObjectName("txt_noticia")
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 190, 131, 51))
        self.groupBox.setObjectName("groupBox")
        self.si = QtGui.QRadioButton(self.groupBox)
        self.si.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.si.setObjectName("si")
        self.no = QtGui.QRadioButton(self.groupBox)
        self.no.setGeometry(QtCore.QRect(80, 30, 51, 21))
        self.no.setObjectName("no")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 91, 16))
        self.label.setFrameShape(QtGui.QFrame.Panel)
        self.label.setObjectName("label")
        self.cmb_ctg = QtGui.QComboBox(self.centralWidget)
        self.cmb_ctg.setGeometry(QtCore.QRect(190, 230, 171, 23))
        self.cmb_ctg.setObjectName("cmb_ctg")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(190, 200, 81, 16))
        self.label_2.setFrameShape(QtGui.QFrame.Panel)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 57, 15))
        self.label_3.setFrameShape(QtGui.QFrame.Panel)
        self.label_3.setObjectName("label_3")
        self.mes = QtGui.QLineEdit(self.centralWidget)
        self.mes.setGeometry(QtCore.QRect(120, 10, 41, 23))
        self.mes.setObjectName("mes")
        self.year = QtGui.QLineEdit(self.centralWidget)
        self.year.setGeometry(QtCore.QRect(170, 10, 71, 23))
        self.year.setObjectName("year")
        self.volver = QtGui.QPushButton(self.centralWidget)
        self.volver.setGeometry(QtCore.QRect(260, 270, 121, 41))
        self.volver.setObjectName("volver")
        formulario.setCentralWidget(self.centralWidget)

        self.retranslateUi(formulario)
        QtCore.QMetaObject.connectSlotsByName(formulario)

    def retranslateUi(self, formulario):
        formulario.setWindowTitle(QtGui.QApplication.translate("formulario", "Agregar Noticia", None, QtGui.QApplication.UnicodeUTF8))
        self.add.setText(QtGui.QApplication.translate("formulario", "agregar noticia", None, QtGui.QApplication.UnicodeUTF8))
        self.t_noticia.setPlaceholderText(QtGui.QApplication.translate("formulario", "Titulo noticia", None, QtGui.QApplication.UnicodeUTF8))
        self.resumen.setPlaceholderText(QtGui.QApplication.translate("formulario", "Resumen", None, QtGui.QApplication.UnicodeUTF8))
        self.dia.setText(QtGui.QApplication.translate("formulario", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.autor.setPlaceholderText(QtGui.QApplication.translate("formulario", "Autor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("formulario", "Publicada?", None, QtGui.QApplication.UnicodeUTF8))
        self.si.setText(QtGui.QApplication.translate("formulario", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.no.setText(QtGui.QApplication.translate("formulario", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("formulario", "Texto Noticia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("formulario", "Categoría?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("formulario", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.mes.setText(QtGui.QApplication.translate("formulario", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.year.setText(QtGui.QApplication.translate("formulario", "0000", None, QtGui.QApplication.UnicodeUTF8))
        self.volver.setText(QtGui.QApplication.translate("formulario", "Volver", None, QtGui.QApplication.UnicodeUTF8))

