# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_portal_adm.ui'
#
# Created: Sat Sep  3 13:08:28 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_portal_adm(object):
    def setupUi(self, portal_adm):
        portal_adm.setObjectName("portal_adm")
        portal_adm.resize(420, 269)
        portal_adm.setMinimumSize(QtCore.QSize(420, 269))
        portal_adm.setMaximumSize(QtCore.QSize(420, 269))
        self.centralWidget = QtGui.QWidget(portal_adm)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setFrameShadow(QtGui.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setObjectName("label")
        self.mstr = QtGui.QPushButton(self.centralWidget)
        self.mstr.setGeometry(QtCore.QRect(20, 130, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mstr.setFont(font)
        self.mstr.setObjectName("mstr")
        self.a_ctgr = QtGui.QPushButton(self.centralWidget)
        self.a_ctgr.setGeometry(QtCore.QRect(120, 130, 81, 23))
        self.a_ctgr.setObjectName("a_ctgr")
        self.a_ntc = QtGui.QPushButton(self.centralWidget)
        self.a_ntc.setGeometry(QtCore.QRect(120, 170, 81, 23))
        self.a_ntc.setObjectName("a_ntc")
        self.ed_ctgr = QtGui.QPushButton(self.centralWidget)
        self.ed_ctgr.setGeometry(QtCore.QRect(220, 130, 81, 23))
        self.ed_ctgr.setObjectName("ed_ctgr")
        self.ed_ntc = QtGui.QPushButton(self.centralWidget)
        self.ed_ntc.setGeometry(QtCore.QRect(220, 170, 81, 23))
        self.ed_ntc.setObjectName("ed_ntc")
        self.el_ctgr = QtGui.QPushButton(self.centralWidget)
        self.el_ctgr.setGeometry(QtCore.QRect(320, 130, 81, 23))
        self.el_ctgr.setObjectName("el_ctgr")
        self.el_ntc = QtGui.QPushButton(self.centralWidget)
        self.el_ntc.setGeometry(QtCore.QRect(320, 170, 81, 23))
        self.el_ntc.setObjectName("el_ntc")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 61, 21))
        self.label_2.setFrameShape(QtGui.QFrame.Box)
        self.label_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(120, 100, 81, 21))
        self.label_3.setFrameShape(QtGui.QFrame.Box)
        self.label_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(220, 100, 81, 21))
        self.label_4.setFrameShape(QtGui.QFrame.Box)
        self.label_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(320, 100, 81, 21))
        self.label_5.setFrameShape(QtGui.QFrame.Box)
        self.label_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.volver = QtGui.QPushButton(self.centralWidget)
        self.volver.setGeometry(QtCore.QRect(110, 212, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setBold(True)
        self.volver.setFont(font)
        self.volver.setObjectName("volver")
        portal_adm.setCentralWidget(self.centralWidget)

        self.retranslateUi(portal_adm)
        QtCore.QMetaObject.connectSlotsByName(portal_adm)

    def retranslateUi(self, portal_adm):
        portal_adm.setWindowTitle(QtGui.QApplication.translate("portal_adm", "Portal", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("portal_adm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-style:italic;\">Escoja la categoría</span></p><p align=\"center\"><span style=\" font-size:12pt; font-style:italic;\">que desea ejecutar:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.mstr.setText(QtGui.QApplication.translate("portal_adm", "Mostrar", None, QtGui.QApplication.UnicodeUTF8))
        self.a_ctgr.setText(QtGui.QApplication.translate("portal_adm", "Categoria", None, QtGui.QApplication.UnicodeUTF8))
        self.a_ntc.setText(QtGui.QApplication.translate("portal_adm", "Noticia", None, QtGui.QApplication.UnicodeUTF8))
        self.ed_ctgr.setText(QtGui.QApplication.translate("portal_adm", "Categoria", None, QtGui.QApplication.UnicodeUTF8))
        self.ed_ntc.setText(QtGui.QApplication.translate("portal_adm", "Noticia", None, QtGui.QApplication.UnicodeUTF8))
        self.el_ctgr.setText(QtGui.QApplication.translate("portal_adm", "Categoria", None, QtGui.QApplication.UnicodeUTF8))
        self.el_ntc.setText(QtGui.QApplication.translate("portal_adm", "Noticia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("portal_adm", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Grilla</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("portal_adm", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Agregar</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("portal_adm", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Editar</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("portal_adm", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Eliminar</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.volver.setText(QtGui.QApplication.translate("portal_adm", "Salir", None, QtGui.QApplication.UnicodeUTF8))

